# Generated by Django 5.2.3 on 2025-06-29 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('exchange', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('isin', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('index', 'Index')], default='stock', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'symbol',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('last_run', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=15)),
                ('error_message', models.TextField()),
                ('duration_seconds', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sync_log',
            },
        ),
        migrations.CreateModel(
            name='Ohlc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('open', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('volume', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlc', to='tradingview.symbol')),
            ],
            options={
                'db_table': 'ohlc',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='tradingview.symbol')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('earnings', 'Earnings'), ('split', 'Split'), ('fork', 'Fork'), ('other', 'Other')], max_length=100)),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tradingview.symbol')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('rsi', 'RSI'), ('macd', 'MACD')], max_length=15)),
                ('value', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical', to='tradingview.symbol')),
            ],
            options={
                'db_table': 'technical',
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='tradingview.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watch_list',
            },
        ),
    ]
