# Generated by Django 5.2.3 on 2025-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
