# Generated by Django 5.2.3 on 2025-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0004_alter_symbol_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
