# Generated by Django 5.2.3 on 2025-07-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0005_alter_symbol_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
