# Generated by Django 5.2.3 on 2025-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0007_profile_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
