# Generated by Django 5.2.3 on 2025-07-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0008_rename_post_name_post_title_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_at',
            new_name='timestamp',
        ),
    ]
