# Generated by Django 5.2.3 on 2025-07-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0009_rename_published_at_news_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
