# Generated by Django 5.2.3 on 2025-07-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0011_alter_ohlc_close_alter_ohlc_high_alter_ohlc_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlc',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
