# Generated by Django 5.2.3 on 2025-07-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0012_alter_ohlc_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
