# Generated by Django 5.2.3 on 2025-07-17 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0013_alter_symbol_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_event_executions'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('symbol', 'title'), name='unique_news_executions'),
        ),
        migrations.AddConstraint(
            model_name='ohlc',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_ohlc_executions'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('symbol', 'user', 'profile'), name='unique_post_executions'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('user', 'id_user'), name='unique_profile_executions'),
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(fields=('symbol', 'slug'), name='unique_symbol_executions'),
        ),
        migrations.AddConstraint(
            model_name='technical',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_technical_executions'),
        ),
    ]
