# Generated by Django 5.2.3 on 2025-07-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0014_event_unique_event_executions_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_executions',
        ),
        migrations.RemoveConstraint(
            model_name='news',
            name='unique_news_executions',
        ),
        migrations.RemoveConstraint(
            model_name='ohlc',
            name='unique_ohlc_executions',
        ),
        migrations.RemoveConstraint(
            model_name='technical',
            name='unique_technical_executions',
        ),
    ]
