# Generated by Django 5.2.3 on 2025-07-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0015_remove_event_unique_event_executions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
    ]
